---
title: "DSA 8020 Project 1"
author: "saransh rakshak"
output:
  pdf_document:
    toc: true
    toc_depth: 3
    latex_engine: xelatex
---

# Instructions

For each problem, your answer should include the following elements:

- A descriptive summary of the data using summary statistics and at least
one plot/graph or table. Give your description in paragraph form.

- An appropriate inferential analysis to address the question. This may be a
confidence interval, hypothesis test, or both. You can use the α value/confidence
level of your choice. If you perform a hypothesis test, state the hypotheses, test
statistic, p-value, decision, and conclusion. If you create a confidence interval,
state the confidence level and provide an interpretation of the interval.

- A thoughtful conclusion that summarizes your findings. You should also dis-
cuss any limitations or complications of your analysis. This should
include the following:

    * An assessment of whether the modeling assumptions are reasonable.
    
    * Discussion of any unusual features of the data. For example, do outliers/high leverage points affect your results?
    
---

# Problem 1

- Perform a detailed regression analysis using the gala data set. Use Endemics as
the response variable, excluding Species from this analysis, to address the following
questions:

```{r loadgaladata}
library(faraway)
data(gala)
gala
```


---

## 1. 





























